from __future__ import annotations

PARAM_KEYS = [
    "module_x",
    "module_y",
    "module_z",
    "nx",
    "ny",
    "pitch_x",
    "pitch_y",
    "n",
    "radius",
    "clearance",
    "parent_x",
    "parent_y",
    "parent_z",
    "child_rmax",
    "child_hz",
    "rmax1",
    "rmax2",
    "x1",
    "x2",
    "y1",
    "y2",
    "z1",
    "z2",
    "z3",
    "r1",
    "r2",
    "r3",
    "tilt_x",
    "tilt_y",
    "bool_a_x",
    "bool_a_y",
    "bool_a_z",
    "bool_b_x",
    "bool_b_y",
    "bool_b_z",
    "inner_r",
    "th1",
    "th2",
    "th3",
    "hz",
    "stack_x",
    "stack_y",
    "t1",
    "t2",
    "t3",
    "stack_clearance",
    "nest_clearance",
    "tx",
    "ty",
    "tz",
    "rx",
    "ry",
    "rz",
]

ENTITY_KEYS = [
    "material",
    "particle",
    "physics_list",
    "source_type",
    "output_format",
]

STRUCTURE_LABELS = [
    "nest",
    "grid",
    "ring",
    "stack",
    "shell",
    "single_box",
    "single_tubs",
    "single_sphere",
    "single_cons",
    "single_trd",
    "single_polycone",
    "single_cuttubs",
    "boolean",
    "unknown",
]

TOKEN_LABELS = ["O"] + [f"B-{k}" for k in (PARAM_KEYS + ENTITY_KEYS)] + [
    f"I-{k}" for k in (PARAM_KEYS + ENTITY_KEYS)
]
