from __future__ import annotations

BASE_MATERIAL_ALIASES = {
    "air": "G4_AIR",
    "g4_air": "G4_AIR",
    "空气": "G4_AIR",
    "water": "G4_WATER",
    "g4_water": "G4_WATER",
    "水": "G4_WATER",
    "cesium iodide": "G4_CESIUM_IODIDE",
    "caesium iodide": "G4_CESIUM_IODIDE",
    "csi": "G4_CESIUM_IODIDE",
    "碘化铯": "G4_CESIUM_IODIDE",
    "g4_csi": "G4_CESIUM_IODIDE",
    "g4_cesium_iodide": "G4_CESIUM_IODIDE",
    "g4_cesium-iodide": "G4_CESIUM_IODIDE",
    "silicon": "G4_Si",
    "si": "G4_Si",
    "g4_si": "G4_Si",
    "硅": "G4_Si",
    "copper": "G4_Cu",
    "cu": "G4_Cu",
    "g4_cu": "G4_Cu",
    "铜": "G4_Cu",
    "aluminum": "G4_Al",
    "aluminium": "G4_Al",
    "al": "G4_Al",
    "g4_al": "G4_Al",
    "铝": "G4_Al",
    "concrete": "G4_CONCRETE",
    "g4_concrete": "G4_CONCRETE",
    "混凝土": "G4_CONCRETE",
    "iron": "G4_Fe",
    "fe": "G4_Fe",
    "g4_fe": "G4_Fe",
    "铁": "G4_Fe",
    "steel": "G4_STAINLESS-STEEL",
    "stainless steel": "G4_STAINLESS-STEEL",
    "g4_stainless-steel": "G4_STAINLESS-STEEL",
    "g4_stainless_steel": "G4_STAINLESS-STEEL",
    "钢": "G4_STAINLESS-STEEL",
    "lead": "G4_Pb",
    "pb": "G4_Pb",
    "g4_pb": "G4_Pb",
    "铅": "G4_Pb",
    "tungsten": "G4_W",
    "w": "G4_W",
    "g4_w": "G4_W",
    "钨": "G4_W",
}


BASE_SOURCE_TYPE_ALIASES = {
    "point source": "point",
    "point": "point",
    "点源": "point",
    "点状源": "point",
    "beam": "beam",
    "pencil beam": "beam",
    "collimated beam": "beam",
    "collimated": "beam",
    "束流": "beam",
    "粒子束": "beam",
    "准直束": "beam",
    "plane source": "plane",
    "plane": "plane",
    "面源": "plane",
    "isotropic": "isotropic",
    "各向同性": "isotropic",
}
